katalon-studio/docker-images

README.md
katalon/src/setup/katalon.sh

The new Katalon version has support for profiles, which would be extremely useful for our CI pipeline.

update version to 5.4.1

---

README.md
katalon/src/setup/katalon.sh

Update version of Katalon to 5.10.0

Update katalon to 5.10.0

---

build/build.sh

[STUDIO-1053]

---

src/Dockerfile

Upgrade javax.mail to Improve sending email in docker image instead of override java.security

[STUDIO-1885] Remove override java.security

---

src/Dockerfile

This release relates to the following tickets:
- [STUDIO-1885](https://katalon.atlassian.net/browse/STUDIO-1885)

Release 8.3.5

---

src/Dockerfile

[STUDIO-2146](https://katalon.atlassian.net/browse/STUDIO-2146)

[STUDIO-2146] Upgrade KDI Ubuntu version to 20.04

---

.github/workflows/workflow.yml

Official Release 8.5.2

---

.github/workflows/workflow.yml

Release Docker Image for Katalon Studio version 8.6.8

Official Release 8.6.8

---

.github/workflows/workflow.yml
src/scripts/setup.sh

Build Katalon Docker for version 9.0.0

Official release 9.0.0

---

.github/workflows/workflow.yml

Official release of Docker Image Katalon Studio 9.3.0

Official release 9.3.0

---

src/scripts/setup.sh

Resolve: https://katalon.atlassian.net/browse/STUDIO-5045

[STUDIO-5045] Updates Gradle from 5.4.1 to 7.6.4

---

.github/workflows/workflow-harden.yml
src/Dockerfile.harden
src/scripts/setup-harden.sh

CO-3006: Update setup scripts to remove webdrivermanager.jar

---

.github/workflows/workflow-ecr.yml

The description does not support markdown, need to update

[STUDIO-6141] Update the URL in description of ECR workflow

---

.github/workflows/workflow-ecr.yml
build/build-for-ecr.sh
src/Dockerfile
src/Dockerfile.slim

- Build ARM64 and AMD64 on ECR
- Change base image for normal and harden images

Build for testing 10.0.0

---

.github/workflows/workflow-ecr.yml
.github/workflows/workflow-slim.yml
.github/workflows/workflow.yml
src/scripts/setup-slim.sh
src/scripts/setup.sh

https://katalon.atlassian.net/browse/STUDIO-6562

Adapt KRE download links uploaded by both Azure DevOps and GitHub Action

---

src/Dockerfile
src/Dockerfile.slim
src/scripts/setup-slim.sh
src/scripts/setup.sh

Move Browser Installation from Golden Image to Studio Image

CO-3548: Move Browser Installation from Golden Image to Studio Image

---

src/Dockerfile
src/Dockerfile.slim
src/scripts/setup-slim.sh
src/scripts/setup.sh

Reverts katalon-studio/docker-images#201

Revert "CO-3527: Fix build for non-root user "

---

src/Dockerfile
src/Dockerfile.slim
src/scripts/setup-slim.sh
src/scripts/setup.sh

Move Browser Installation from Golden Image to Studio Image

CO-3693: Move Browser Installation from Golden Image to Studio Image

---

src/scripts/setup-slim.sh
src/scripts/setup.sh

Fix: Update apt-get update

---

src/Dockerfile
src/Dockerfile.slim
src/scripts/setup-slim.sh
src/scripts/setup.sh

Create Golden image Ubuntu 24.04

CO-3694, CO-3389: Create Golden image Ubuntu 24.04

---

.github/workflows/workflow-slim.yml
.github/workflows/workflow.yml

Adjust Studio pipelines to authenticate with a Docker Hub token

CO-3732: Adjust Studio pipelines to authenticate with a Docker Hub token

---

src/Dockerfile
src/Dockerfile.slim

Fix CVE-2025-22871, CVE-2023-50782 and CVE-2024-26130

Update(base-image): Fix CVE-2025-22871, CVE-2023-50782 and CVE-2024-26130
